Be 1 init application
viktoriya-okseniuk/meduzzen-back pull request #1
Opened 2023-10-23 17:01 UTC by viktoriya-okseniuk

2023-10-23 19:28 UTC, Ivanus-Volodymyr requested changes

2023-10-23 19:28 UTC, Ivanus-Volodymyr commented on README.md
need a description for .env

2023-10-23 19:28 UTC, Ivanus-Volodymyr commented on src/app.controller.ts
> +  healthChecker(): object {
add async and types
object is not good decision

2023-10-23 19:28 UTC, Ivanus-Volodymyr commented on src/app.service.ts
> +  healthCheck(): object {
add async and types
object is not good decision

2023-10-24 12:49 UTC, Ivanus-Volodymyr requested changes

2023-10-24 12:49 UTC, Ivanus-Volodymyr commented on src/app.service.ts
Very complicated logic for checking server status

2023-10-24 13:25 UTC, Ivanus-Volodymyr requested changes

2023-10-24 13:25 UTC, Ivanus-Volodymyr commented on src/app.service.ts
> +  }
check in the task what the form of the server status response should be  
do not use JSON.stringify(obj)

also do not forget change types

2023-10-25 11:38 UTC, viktoriya-okseniuk commented on src/app.service.ts
> +  }
Please check if i done it well

2023-10-25 15:51 UTC, Ivanus-Volodymyr requested changes

2023-10-25 15:51 UTC, Ivanus-Volodymyr commented on src/app.controller.ts
> +    const result: string = await this.appService.healthCheck();
make it in one line

2023-10-25 15:51 UTC, Ivanus-Volodymyr commented on src/app.service.ts
> +  }
do not use template string
check task please

2023-10-25 17:52 UTC, merged