BE-4-add-migratiions
viktoriya-okseniuk/meduzzen-back pull request #4
Opened 2023-11-01 15:02 UTC by viktoriya-okseniuk

2023-11-01 15:20 UTC, Ivanus-Volodymyr requested changes

2023-11-01 15:20 UTC, Ivanus-Volodymyr commented on src/app.service.ts
> +    return {'status_code': 200, 'detail': 'ok', 'result': 'working'}
use HttpStatus

2023-11-01 15:20 UTC, Ivanus-Volodymyr commented on src/logger/logger.service.ts
> +}
extend

2023-11-01 17:32 UTC, viktoriya-okseniuk commented on src/app.service.ts
> +    return {'status_code': 200, 'detail': 'ok', 'result': 'working'}
Http code works on local , but not working in Docker. need to figure it out((

2023-11-02 16:01 UTC, Ivanus-Volodymyr requested changes

2023-11-02 16:01 UTC, Ivanus-Volodymyr commented on src/app.service.ts
> +    return {'status_code': 200, 'detail': 'ok', 'result': 'working'}
HttpStatus.OK

2023-11-02 17:01 UTC, merged